services:
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD:/etc/selenoid"
      - "$PWD/build/selenoid/video:/opt/selenoid/video"
      - "$PWD/build/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/build/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]

  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:latest-release
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
